(async()=>{
const $=id=>document.getElementById(id),room=$('room'),state=$('state'),host=$('viewport');
const stateField=$('state-field'),stateHome=stateField.parentElement,mobileLayout=matchMedia('(max-width:1000px)');
function arrange(){if(mobileLayout.matches)$('mobile-state').append(stateField);else stateHome.insertBefore(stateField,$('state-note'));}
mobileLayout.addEventListener('change',arrange);arrange();
let data,mode='3d',scene,camera,renderer,controls,outline,dirty=false,active=true,custom={};
const coarse=matchMedia('(pointer:coarse)').matches||innerWidth<=720,reduce=matchMedia('(prefers-reduced-motion:reduce)').matches;
const roomNames={whole:'全屋',living:'客餐厅',master:'主卧',second:'次卧',kitchen:'厨房与设备',bath:'卫生间',balcony:'主阳台','entry-eye':'入户视角'};
const labels={'master-bed':'主卧床','second-bed':'次卧床','master-wardrobe':'主卧衣柜','second-wardrobe':'次卧衣柜',vanity:'梳妆组合','vanity-stool':'梳妆凳','master-door-cabinet':'主卧门头柜','second-window-cabinet':'窗下浅柜',sofa:'沙发','tv-unit':'电视低柜','tv-screen':'电视','tv-upper':'电视浅上柜','dining-table':'餐桌','dining-chair-north':'北餐椅','dining-chair-south':'南餐椅','shoe-bag-cabinet':'鞋包柜',fridge:'冰箱安装组合','oven-tower':'蒸烤/微波柜',robot:'机器人组合',sideboard:'浅餐边柜','service-scribe':'末端收口',kitchen:'厨房组合',purifier:'净水器',shower:'淋浴湿区','bath-basin':'洗手盆柜','bath-mirror':'浴室镜柜',toilet:'马桶',washer:'洗衣机','laundry-counter':'独立洗衣台','water-heater':'燃气热水器','utility-storage':'生活阳台低柜','balcony-housekeeping':'家政柜','drying-rack':'晾衣架','ac-master':'主卧挂机','ac-second':'次卧挂机','ac-living':'客厅挂机','entry-door':'户门','master-door':'主卧门','second-door':'次卧门','bath-door':'浴室门','kitchen-door':'厨房门','balcony-door':'阳台门'};
const notes={S12:'主阳台洗衣装卸：机器门开启，晾衣架保持收起，前方不挂衣物。','S12-extract':'关门后整机向前抽出700毫米；处理水电连接后维护，阳台暂停其他作业。',S00:'关闭态。过门后主路线按1100毫米目标控制；户门实际净口另定。',S02:'两把餐椅各后拉350毫米。东侧为主路线，桌西侧不是备用绕行通路。',S04:'取热盘临时占用主路，请暂停对穿。不能沿用关闭态1100毫米标签。',S08:'次床抽屉打开后至衣柜前剩454毫米，对应衣柜门关闭。',S07:'主床尾抽打开后至窗侧墙剩496毫米，梳妆凳收起。',S10:'先移开床垫，再拆台板取物。这是维护操作，不是整床翻转。',S11:'补水/取箱为临时作业。检修台盖打开，上方不是固定备餐面。',S13:'晾衣架下降及挂衣会遮挡视线，阳台此时为家政作业区。',S14:'线框为设备维护空域，实际滤网、梯凳和管路条件依机型落实。',S19:'柜面前350毫米用于换芯，不等同于完整拆机。',S20:'整机向前取出600毫米，须先完成适用的断水、断电和管线处理。'};
const itemNotes={'master-bed':'床垫1500×2000；床侧440/599，床尾846。固定床架、浅抽屉及上取分仓。','second-bed':'床垫1500×2000；床侧804、床尾402；单侧上下床。','second-wardrobe':'下部三只500箱；上柜1240宽，北端留空调服务缺口。衣柜和床抽分时操作。',fridge:'安装段750×700，距沙发末端沿墙1570。与餐桌间1139；散热、开门及内部抽屉取出按机型。',sideboard:'入口端350深，台面830×350，上柜退台；不能改成600深通高柜。','shoe-bag-cabinet':'鞋长沿柜宽横放，常用鞋在南格。柜前是取物区，不是主通路。',vanity:'750宽，台面750、膝部至少650；镜盒可闭，薄抽与凳分状态。','second-window-cabinet':'700×280×800，柜前727；进入处仍有402窄颈，用于低频小件。','balcony-housekeeping':'450宽×560深×2200高，双窄门朝阳台中央；180长物格＋216层板格，侧向固定门边实墙，不锚栏杆。',shower:'主湿区内净900×959，窗凹位并入。不能由洁具图形反推排污接口。','water-heater':'独立设备预留，不封普通密闭柜；燃气及专用排烟由专业设计。',washer:'主阳台右端630×660安装位。已有给水排水；污废水接法、防雨、供电按现场与机型落实，不能只靠防护网。','utility-storage':'原洗衣位改700×680×925低柜，燃气热水器及检修空间不动。','laundry-counter':'700×700整衣台，底900、顶925，独立支承。上方不加吊柜，不再开第二个洗衣盆。',purifier:'独立297柜，前维护350、整机取出600；设备与接管可拆。','ac-living':'电视墙近阳台一端，与浅上柜分开；出风和冷量按实际机型。'};
function invalidate(){if(dirty||!renderer||!active)return;dirty=true;requestAnimationFrame(draw);}
function theme(){const v=$('theme').value;document.documentElement.dataset.theme=v==='auto'?(matchMedia('(prefers-color-scheme:dark)').matches?'dark':'light'):v;invalidate();}
$('theme').onchange=theme;theme();
function preview(){const r=room.value==='entry-eye'?'whole':room.value,st=mode==='static'&&state.value!=='S00'&&data?.staticViews?.[state.value];$('preview').src=st?'images/'+st.file:'images/'+r+(mode==='plan'?'-plan.svg':'.png');$('preview').alt=(st?state.selectedOptions[0].textContent:roomNames[room.value])+'设计视图';$('preview-caption').textContent=st?'所选工况的三维状态图；切换三维可连续操作。':'关闭态'+(mode==='plan'?'平面，可用浏览器缩放。':'三维备用视图。');}
function modeTo(m){mode=m;host.hidden=m!=='3d';$('static-view').hidden=m==='3d';state.disabled=m==='plan'||!data;$('progress').disabled=m!=='3d';$('selected-open').disabled=m!=='3d'||!$('item').value;const customOption=state.querySelector('option[value="CUSTOM"]');if(customOption)customOption.disabled=m!=='3d';if(m!=='3d'&&state.value==='CUSTOM')state.value='S00';document.querySelector('.camera-controls').hidden=m!=='3d';for(const [id,v] of [['mode3d','3d'],['modeplan','plan'],['modestatic','static']])$(id).setAttribute('aria-pressed',String(m===v));preview();if(m!=='3d')$('state-note').textContent=m==='plan'?'当前为关闭态平面，家具尺寸仍可查阅。':(notes[state.value]||'静态工况图，不需要WebGL。');else if(renderer)update();resize();invalidate();}
$('mode3d').onclick=()=>modeTo('3d');$('modeplan').onclick=()=>modeTo('plan');$('modestatic').onclick=()=>modeTo('static');
function fail(msg){$('loading').textContent=msg;$('mode3d').disabled=true;modeTo('static');$('state-note').textContent=msg+'，仍可查看平面、备用图和尺寸。';}
try{const res=await fetch('scene-public.json');if(!res.ok)throw Error(res.status);data=await res.json();}catch(e){fail('模型加载失败');return;}
const itemMap=Object.fromEntries(data.items.map(x=>[x.id,x]));
state.replaceChildren(...data.states.map(s=>Object.assign(document.createElement('option'),{value:s.id,textContent:s.name})));
state.append(Object.assign(document.createElement('option'),{value:'CUSTOM',textContent:'选件开合'}));
labels['bath-tap']='洗面龙头';
for(const i of data.items){if(['ceiling-light','finish-layer'].includes(i.recipe))continue;const op=document.createElement('option');op.value=i.id;op.textContent=i.label+' '+(labels[i.id]||i.id);$('item').append(op);}
let remembered=null;try{remembered=JSON.parse(localStorage.getItem('house-design-v2')||'null');if(remembered){if(roomNames[remembered.room])room.value=remembered.room;if(data.states.some(x=>x.id===remembered.state))state.value=remembered.state;$('walls').checked=!!remembered.walls;if(['auto','dark','light'].includes(remembered.theme))$('theme').value=remembered.theme;if(itemMap[remembered.item])$('item').value=remembered.item;}}catch(_){}
function select(id){const i=itemMap[id];if(!i)return;const d=i.dimensionsMm,along=i.face==='-X'||i.face==='+X',strong=document.createElement('strong'),p=document.createElement('p'),n=document.createElement('p');strong.textContent=labels[id]||id;p.textContent='完成组合外包 '+Math.round(along?d[2]:d[0])+'×'+Math.round(along?d[0]:d[2])+'×'+Math.round(d[1])+' mm；底 '+Math.round(i.bounds[1]*1000)+'，顶 '+Math.round(i.bounds[4]*1000)+' mm。';n.textContent=itemNotes[id]||'设计控制尺寸；安装口、内部净格及使用状态分别表达。';$('item-detail').replaceChildren(strong,p,n);$('selected-open').disabled=mode!=='3d'||!data.parts.some(p=>p.owner===id&&(p.hinge||p.motion));if(outline){outline.box.set(new THREE.Vector3(...i.bounds.slice(0,3)),new THREE.Vector3(...i.bounds.slice(3)));outline.visible=true;invalidate();}}
$('item').onchange=()=>{const id=$('item').value,i=itemMap[id],target=i&&({'7':'master','3':'second','4':'bath','13':'kitchen','0':'balcony','12':'living'})[i.room];if(target&&room.value!=='whole'&&room.value!==target){room.value=target;if(renderer)setView();else preview();} $('selected-open').setAttribute('aria-pressed','false');select(id);};
room.onchange=()=>{if(mode==='static')state.value='S00';preview();save();};
state.onchange=()=>{if(mode==='static'){const v=data?.staticViews?.[state.value];if(v)room.value=v.room;preview();$('state-note').textContent=notes[state.value]||'所选工况静态图。';save();}};
if(new URLSearchParams(location.search).has('fallback')){fail('已选择备用模式');return;}
if(!window.THREE||!THREE.OrbitControls){fail('三维组件不可用');return;}
const T=THREE;scene=new T.Scene();camera=new T.PerspectiveCamera(42,1,.05,100);
try{renderer=new T.WebGLRenderer({antialias:!coarse,alpha:true,preserveDrawingBuffer:true});}catch(e){fail('浏览器未启用WebGL');return;}
renderer.setPixelRatio(Math.min(devicePixelRatio,coarse?1.25:2));renderer.outputEncoding=T.sRGBEncoding;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=.95;renderer.localClippingEnabled=true;renderer.setClearColor(0xffffff,0);renderer.shadowMap.enabled=false;renderer.shadowMap.type=T.PCFSoftShadowMap;host.prepend(renderer.domElement);
controls=new T.OrbitControls(camera,renderer.domElement);controls.enableDamping=!reduce;controls.dampingFactor=.13;controls.minDistance=.6;controls.maxDistance=35;controls.maxPolarAngle=Math.PI*.495;
scene.add(new T.HemisphereLight(0xffffff,0x819093,.75));const sun=new T.DirectionalLight(0xffffff,.65);sun.position.set(-5,12,8);sun.castShadow=false;sun.shadow.mapSize.set(1024,1024);Object.assign(sun.shadow.camera,{left:-9,right:9,top:10,bottom:-10});sun.shadow.bias=-.0007;scene.add(sun);
const clip=new T.Plane(new T.Vector3(0,-1,0),.9),mats={},edgeMats=[];
for(const[k,m]of Object.entries(data.materials))mats[k]=new T.MeshStandardMaterial({color:new T.Color(m.color).convertSRGBToLinear(),roughness:m.metalness?.4:.85,metalness:m.metalness,side:T.DoubleSide,transparent:m.alpha<1,opacity:m.alpha,depthWrite:m.alpha===1});
mats['source-window']=mats.glass.clone();
const root=new T.Group();scene.add(root);
for(const g of data.shell){const geo=new T.BufferGeometry();geo.setAttribute('position',new T.Float32BufferAttribute(g.positions,3));geo.setIndex(g.indices);geo.computeVertexNormals();const mesh=new T.Mesh(geo,mats[g.kind==='window'?'source-window':g.kind]);mesh.receiveShadow=true;mesh.castShadow=g.kind==='wall';root.add(mesh);}
const groups={};for(const h of data.hinges){const g=new T.Group();g.position.fromArray(h.pivot);root.add(g);groups[h.id]=g;}root.updateMatrixWorld(true);for(const h of data.hinges)if(h.parent)groups[h.parent].attach(groups[h.id]);
const partMeshes=[],pickable=[];
for(const p of data.parts){let geo;if(p.shape==='cylinder'){geo=new T.CylinderGeometry(.5,.5,1,24);geo.scale(...p.size);if(p.axis==='z')geo.rotateX(Math.PI/2);if(p.axis==='x')geo.rotateZ(Math.PI/2);}else geo=new T.BoxGeometry(...p.size);const m=new T.Mesh(geo,mats[p.material]);m.position.fromArray(p.position);m.userData=p;m.name=p.id;m.castShadow=p.material!=='glass';m.receiveShadow=true;root.add(m);if(p.hinge){root.updateMatrixWorld(true);groups[p.hinge].attach(m);}const em=new T.LineBasicMaterial({color:0x5c6d73,transparent:true,opacity:.22});edgeMats.push(em);if(!['glass','mirror','light'].includes(p.material))m.add(new T.LineSegments(new T.EdgesGeometry(geo,35),em));partMeshes.push({mesh:m,p,base:m.position.clone()});if(!['lighting','finish'].includes(p.role))pickable.push(m);}
const envMeshes={};for(const e of data.envelopes){const b=e.bounds,m=new T.Mesh(new T.BoxGeometry(b[3]-b[0],b[4]-b[1],b[5]-b[2]),new T.MeshBasicMaterial({color:e.kind.includes('clothing')?0x648d96:0xb07632,transparent:true,opacity:.13,depthWrite:false}));m.position.set((b[0]+b[3])/2,(b[1]+b[4])/2,(b[2]+b[5])/2);m.visible=false;scene.add(m);envMeshes[e.id]=m;}
outline=new T.Box3Helper(new T.Box3(),0x246b83);outline.visible=false;scene.add(outline);
const routeLine=new T.Line(new T.BufferGeometry().setFromPoints(data.routes[0].pointsXZ.map(p=>new T.Vector3(p[0]/1000,.025,p[1]/1000))),new T.LineBasicMaterial({color:0x397b72}));scene.add(routeLine);
const dims=[['master',[-2.966,.12,-1.5],[-2.526,.12,-1.5],'440'],['master',[-.996,.12,-2],[-.397,.12,-2],'599'],['master',[-1.8,.12,-3.673],[-1.8,.12,-2.827],'846'],['second',[-2.27,.12,1],[-1.466,.12,1],'804'],['second',[-2.9,.12,-.647],[-2.9,.12,-.245],'402'],['living',[2.56,.12,4],[3.789,.12,4],'1229'],['living',[.623,.12,-1.6],[2.939,.12,-1.6],'2316'],['kitchen',[.193,.9,5.2],[2.44,.9,5.2],'2247'],['bath',[-1.897,.08,3],[-.997,.08,3],'900'],['balcony',[3.199,2.23,-3.3],[3.759,2.23,-3.3],'560']].map(([v,a,b,text])=>{const line=new T.Line(new T.BufferGeometry().setFromPoints([new T.Vector3(...a),new T.Vector3(...b)]),new T.LineBasicMaterial({color:0x365a68}));scene.add(line);const el=document.createElement('span');el.className='dim'+(text==='402'?' warning':'');el.textContent=text+' mm';$('measure-labels').append(el);return{v,a,b,text,line,el};});
function factor(key){return(state.value==='CUSTOM'?(custom[key]||0):(data.states.find(s=>s.id===state.value)?.motions[key]||0))*Number($('progress').value)/100;}
$('selected-open').onclick=()=>{const id=$('item').value,on=$('selected-open').getAttribute('aria-pressed')!=='true';custom={};for(const p of data.parts.filter(p=>p.owner===id)){if(p.motion&&p.motion.name!=='washerExtract')custom[p.motion.name]=on?1:0;if(p.hinge){const h=data.hinges.find(h=>h.id===p.hinge);if(h)custom[h.motion]=on?1:0;}}state.value='CUSTOM';$('selected-open').setAttribute('aria-pressed',String(on));update();};
function save(){try{localStorage.setItem('house-design-v2',JSON.stringify({room:room.value,state:state.value,walls:$('walls').checked,theme:$('theme').value,item:$('item').value}));}catch(_){}}
function update(){
 for(const h of data.hinges){let f=factor(h.motion);if(h.motion==='dishwasher')f=Math.min(1,f/.6);if(h.until)f=Math.min(1,f/h.until);groups[h.id].rotation[h.axis]=h.angle*f;}
 const top=factor('bedTopAccess')>.5;
 for(const{mesh,p,base}of partMeshes){mesh.position.copy(base);if(p.motion?.delta){let f=factor(p.motion.name);if(p.motion.start)f=Math.max(0,(f-p.motion.start)/(1-p.motion.start));mesh.position.addScaledVector(new T.Vector3(...p.motion.delta),f);}mesh.visible=!(top&&['mattress','pillow','removable-bed-panel'].includes(p.role))&&(p.role!=='lighting'||$('lighting').checked);if(p.role==='cable'){const f=factor('drying-rack-lower');mesh.scale.y=1+f*.9/.27;mesh.position.y=base.y-f*.45;}}
 const s=data.states.find(s=>s.id===state.value);for(const[id,m]of Object.entries(envMeshes))m.visible=$('envelopes').checked&&(s?.envelopes||[]).includes(id);
 routeLine.visible=$('dimensions').checked&&['whole','living','entry-eye'].includes(room.value)&&['S00','S02'].includes(state.value);
 $('state-note').textContent=notes[state.value]||(s?.routeMode==='maintenance'?'维护状态，设备型号、接口与维修动作按实际条件落实。':'开启包络为设计运动示意，不是厂家五金或施工认证。');outline.visible=false;save();invalidate();
}
const bounds={master:[-3.086,0,-3.8,.323,2.8,-.647],second:[-3.94,0,-1.4,-.746,2.8,1.935],living:[-.75,0,-3.06,3.91,2.8,5.3],kitchen:[-1.2,0,3.12,2.56,2.8,5.31],bath:[-2.43,0,1.815,.323,2.8,3.63],balcony:[.323,0,-4.91,3.91,2.8,-2.93],whole:[-3.941,0,-4.908,3.909,2.8,5.307]};
function setView(){const key=room.value,b=bounds[key]||bounds.whole;camera.position.fromArray(key==='whole'?[-11,16,15]:(data.views[key]?.eye||data.views.whole.eye));controls.target.fromArray(data.views[key]?.target||[0,.7,.25]);const planes=[];
 if(!['whole','entry-eye'].includes(key))planes.push(new T.Plane(new T.Vector3(1,0,0),-b[0]),new T.Plane(new T.Vector3(-1,0,0),b[3]),new T.Plane(new T.Vector3(0,0,1),-b[2]),new T.Plane(new T.Vector3(0,0,-1),b[5]));
 for(const[k,m]of Object.entries(mats))m.clippingPlanes=(k==='wall'||k==='source-window')?[...planes,clip]:planes;for(const m of edgeMats)m.clippingPlanes=planes;for(const m of Object.values(envMeshes))m.material.clippingPlanes=planes;outline.material.clippingPlanes=planes;
 if(key==='entry-eye')$('walls').checked=true;clip.constant=$('walls').checked?3.2:.9;
 if(key!=='entry-eye'){controls.target.set((b[0]+b[3])/2,.9,(b[2]+b[5])/2);for(let i=0;i<3;i++){camera.lookAt(controls.target);camera.updateMatrixWorld(true);const pts=[];for(const x of[b[0],b[3]])for(const y of[0,2.8])for(const z of[b[2],b[5]])pts.push(new T.Vector3(x,y,z).project(camera));const f=Math.max(...pts.map(p=>Math.max(Math.abs(p.x),Math.abs(p.y))))/.96;camera.position.sub(controls.target).multiplyScalar(f).add(controls.target);}}
 controls.update();outline.visible=false;preview();update();
}
function interaction(on){controls.enabled=on;renderer.domElement.style.touchAction=on?'none':'pan-y pinch-zoom';$('touch-mode').setAttribute('aria-pressed',String(on));$('touch-mode').textContent=on?'退出模型操作':'操作3D';}
interaction(!coarse);$('touch-mode').onclick=()=>interaction(!controls.enabled);
room.onchange=()=>{if(mode==='static')state.value='S00';setView();};state.onchange=()=>{if(mode==='static'){const v=data.staticViews?.[state.value];if(v)room.value=v.room;preview();$('state-note').textContent=notes[state.value]||'所选工况静态图。';}else update();};$('progress').oninput=update;for(const id of['walls','dimensions','envelopes','lighting'])$(id).onchange=()=>{clip.constant=$('walls').checked?3.2:.9;update();};
document.querySelectorAll('[data-camera]').forEach(btn=>btn.onclick=()=>{const a=btn.dataset.camera;if(a==='reset'){setView();return;}const v=camera.position.clone().sub(controls.target);if(a==='left'||a==='right')v.applyAxisAngle(new T.Vector3(0,1,0),a==='left'?.25:-.25);else v.multiplyScalar(a==='in'?.84:1.19);if(v.length()>.6&&v.length()<35)camera.position.copy(controls.target).add(v);controls.update();invalidate();});
const ray=new T.Raycaster();let down;renderer.domElement.addEventListener('pointerdown',e=>down=[e.clientX,e.clientY]);renderer.domElement.addEventListener('pointerup',e=>{if(!down||Math.hypot(e.clientX-down[0],e.clientY-down[1])>6)return;const r=renderer.domElement.getBoundingClientRect();ray.setFromCamera(new T.Vector2(2*(e.clientX-r.left)/r.width-1,1-2*(e.clientY-r.top)/r.height),camera);const h=ray.intersectObjects(pickable,false).find(h=>h.object.visible&&!(h.object.material.clippingPlanes||[]).some(p=>p.distanceToPoint(h.point)<0));if(h){$('item').value=h.object.userData.owner;select(h.object.userData.owner);}});
function resize(){if(!renderer||host.hidden)return;renderer.setSize(host.clientWidth,host.clientHeight,false);camera.aspect=host.clientWidth/host.clientHeight;camera.updateProjectionMatrix();invalidate();}
function draw(){dirty=false;if(!active||host.hidden)return;const changed=controls.update();scene.updateMatrixWorld(true);
 for(const d of dims){const show=$('dimensions').checked&&room.value===d.v;d.line.visible=show;d.el.hidden=!show;if(!show)continue;const a=[...d.a],b=[...d.b];let text=d.text;if(d.text==='846'&&state.value==='S07'){b[2]-=.35*factor('MB-drawers');text=String(Math.round(846-350*factor('MB-drawers')));}if(d.text==='804'&&state.value==='S08'){a[0]+=.35*factor('SB-drawers');text=String(Math.round(804-350*factor('SB-drawers')));}d.line.geometry.setFromPoints([new T.Vector3(...a),new T.Vector3(...b)]);d.el.textContent=text+' mm';const p=new T.Vector3(...a).add(new T.Vector3(...b)).multiplyScalar(.5).project(camera);d.el.hidden=p.z>1||p.z< -1||Math.abs(p.x)>1||Math.abs(p.y)>1;d.el.style.left=(p.x+1)*host.clientWidth/2+'px';d.el.style.top=(1-p.y)*host.clientHeight/2+'px';}
 for(const d of dims){if(d.el.hidden||!['599','804'].includes(d.text))continue;const owner=d.text==='599'?'master-wardrobe':'second-wardrobe';let front=itemMap[owner].bounds[0];for(const pm of partMeshes){if(pm.p.owner===owner&&pm.p.position[1]<2.1&&(pm.p.role==='door'||pm.p.role==='drawer'))front=Math.min(front,new T.Box3().setFromObject(pm.mesh).min.x);}const bedEdge=d.text==='599'?-.996:-2.27+.35*factor('SB-drawers');const a=new T.Vector3(bedEdge,.12,d.a[2]),b=new T.Vector3(front,.12,d.b[2]);d.line.geometry.setFromPoints([a,b]);d.el.textContent=Math.round((front-bedEdge)*1000)+' mm';const p=a.add(b).multiplyScalar(.5).project(camera);d.el.style.left=(p.x+1)*host.clientWidth/2+'px';d.el.style.top=(1-p.y)*host.clientHeight/2+'px';}
 renderer.render(scene,camera);if(changed)invalidate();
}
controls.addEventListener('change',invalidate);new ResizeObserver(resize).observe(host);document.addEventListener('visibilitychange',()=>{active=!document.hidden;invalidate();});
theme();resize();setView();if(remembered?.item)select(remembered.item);$('loading').hidden=true;
window.houseViewer={ready:true,parts:data.parts.length,states:data.states.length,setState(id){state.value=id;update();},setRoom(id){room.value=id;setView();},getState(){return{room:room.value,state:state.value,mode,touchEnabled:controls.enabled};}};
})();
